[package]
name = "data_interconverter_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.69"
js-sys = "0.3.45"
web-sys = { version = "0.3.45", features = [ 
    'console', # For console_error_panic_hook and potential direct use
    # Add other web-sys features if your Rust code directly needs them
] }
num-bigint = { version = "0.4", features = ["serde"] } # <<< Serde feature is KEY
num-traits = "0.2" 
anyhow = "1.0"
console_error_panic_hook = { version = "0.1.7", optional = true } 
wasm-bindgen-futures = "0.4.26" 
# lazy_static is no longer needed with text modality removed
serde = { version = "1.0", features = ["derive"] } # derive is needed for AppState if it were serializable
serde-wasm-bindgen = "0.5.0" # For JsValue <-> Rust type (including Vec<BigInt>)

[dev-dependencies]
wasm-bindgen-test = "0.3.26" 

[features]
default = ["console_error_panic_hook"]