[package]
name = "data_interconverter_wasm"
version = "0.1.0"
edition = "2021"
authors = ["BadFoxAI <badfoxai@gmail.com>"] # Optional: Add your author info
description = "A WASM module for interconverting BigInts, Text, and Numerical Sequences." # Optional
# repository = "https://github.com/BadFoxAI/data-interconverter" # Optional
# license = "MIT OR Apache-2.0" # Optional: Choose a license

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Core WASM bindings - using specified older stable versions
wasm-bindgen = "0.2.69"
js-sys = "0.3.45" # Provides JsBigInt, JsArray, etc.
web-sys = { version = "0.3.45", features = [ 
    'console' # For console_error_panic_hook and potential direct logging
    # Add other web-sys features ONLY IF your Rust code DIRECTLY uses them.
    # If your current lib.rs does not use Document, Element, etc., they can be omitted.
    # For safety with your toolchain, keeping the ones you had before is fine:
    # 'Document', 
    # 'Element',
    # 'HtmlElement',
    # 'Window' 
    # The image related ones are definitely not needed now:
    # 'ImageData', 'CanvasRenderingContext2d', 'HtmlCanvasElement', 
    # 'File', 'Blob', 'Url', 'FileReader', 'ProgressEvent', 'EventTarget', 'Node'
] } # <<< Ensure no comma after the last feature if it's the end of the list and before ']'

# Arbitrary-precision integers with Serde support for Vec<BigInt>
num-bigint = { version = "0.4", features = ["serde"] } # "serde" feature is CRUCIAL
num-traits = "0.2" # For Zero, One, Pow, ToPrimitive, Signed etc.

# Error handling
anyhow = "1.0"

# Better panic messages in the browser console
console_error_panic_hook = { version = "0.1.7", optional = true } 

# For async WASM functions if any
wasm-bindgen-futures = "0.4.26" 

# For static, lazily evaluated variables (like CHAR_SET_ARRAY if text modality is present)
lazy_static = "1.4.0" 

# Serialization framework
serde = { version = "1.0", features = ["derive"] }
# Bridge for Serde to wasm-bindgen JsValue, crucial for Vec<BigInt>
serde-wasm-bindgen = "0.4.5" # Using this older version for compatibility

[dev-dependencies]
wasm-bindgen-test = "0.3.26" 

[features]
default = ["console_error_panic_hook"]

# Optional: Profile for release builds (wasm-pack uses --release by default)
# [profile.release]
# lto = true
# opt-level = 's' # Optimize for size