[package]
name = "data_interconverter_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.69"
js-sys = "0.3.45"
web-sys = { version = "0.3.45", features = [ 
    'console',
    'Document', 'Element', 'HtmlElement', 'Window', 'ImageData', 
    'CanvasRenderingContext2d', 'HtmlCanvasElement', 'File', 'Blob', 
    'Url',  'FileReader', 'ProgressEvent', 'EventTarget', 'Node', 
] }
num-bigint = { version = "0.4", features = ["serde"] } 
num-traits = "0.2" 
anyhow = "1.0"
console_error_panic_hook = { version = "0.1.7", optional = true } 
wasm-bindgen-futures = "0.4.26" 
lazy_static = "1.4.0" # Still needed if you plan to reintroduce CHAR_SET_ARRAY quickly
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.5.0" 

[dev-dependencies]
wasm-bindgen-test = "0.3.26" 

[features]
default = ["console_error_panic_hook"]