[package]
name = "data_interconverter_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# These are very old, but very stable versions.
# We are using these specific versions to bypass dependency resolution issues.
wasm-bindgen = "0.2.69"
js-sys = "0.3.45"
web-sys = { version = "0.3.45", features = [
    'console',
    'Document',
    'Element',
    'HtmlElement',
    'Window',
    'ImageData',
    'CanvasRenderingContext2d',
    'HtmlCanvasElement',
    'File',
    'Blob',
    'Url',
    'FileReader',
    'ProgressEvent',
    'EventTarget',
    'Node',
    'Window', # Added Window here as it was in your previous features list
] }
num-bigint = "0.4"
num-traits = "0.2"
anyhow = "1.0"
console_error_panic_hook = { version = "0.1", optional = true }
wasm-bindgen-futures = "0.4" # This was in your toml, ensure it's here
lazy_static = "1.4"         # This should be here, under dependencies
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.5"  # This was in your toml, ensure it's here


[dev-dependencies]
wasm-bindgen-test = "0.3" # This was in your toml, ensure it's here

[features]
default = ["console_error_panic_hook"] # Make sure 'lazy_static' is NOT on this line