[package]
name = "data_interconverter_wasm"
version = "0.1.0"
edition = "2021"
# authors = ["Your Name <you@example.com>"] # Optional: Add your author info
# description = "A WASM module for interconverting data types." # Optional
# repository = "https://github.com/BadFoxAI/data-interconverter" # Optional
# license = "MIT OR Apache-2.0" # Optional: Choose a license

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Core WASM bindings - using specified older stable versions
wasm-bindgen = "0.2.69"
js-sys = "0.3.45"
web-sys = { version = "0.3.45", features = [
    'console',
    # Add other specific web-sys features as needed by your lib.rs
    # For the current streamlined version, only 'console' might be strictly necessary from web-sys
    # If you use Document, Element, Window etc. directly in Rust, add them back.
    # For example:
    # 'Document',
    # 'Element',
    # 'HtmlElement',
    # 'Window',
] }

# Arbitrary-precision integers with Serde support for Vec<BigInt>
num-bigint = { version = "0.4", features = ["serde"] }
num-traits = "0.2" # For Zero, One, Pow, ToPrimitive, Signed etc.

# Error handling
anyhow = "1.0"

# Better panic messages in the browser console
console_error_panic_hook = { version = "0.1.7", optional = true } # Note: 0.1.7 is a common version for 0.1.x series

# For async WASM functions if any (not currently used in AppState methods but good to keep if #[wasm_bindgen(start)] is async)
wasm-bindgen-futures = "0.4.26" # Slightly older but stable version compatible with wasm-bindgen 0.2.69

# For static, lazily evaluated variables
lazy_static = "1.4.0" # Common stable version

# Serialization framework
serde = { version = "1.0", features = ["derive"] }
# Bridge for Serde to wasm-bindgen JsValue, crucial for Vec<BigInt>
serde-wasm-bindgen = "0.5.0" # Ensure compatibility with your wasm-bindgen version if issues arise, 0.5.0 is relatively recent but often works.
                             # If 0.5.0 causes issues with wasm-bindgen 0.2.69, you might try an older serde-wasm-bindgen like 0.4.x,
                             # but 0.5.0 aims for wide compatibility.

[dev-dependencies]
wasm-bindgen-test = "0.3.26" # Matches js-sys/web-sys 0.3.4x versions roughly

[features]
default = ["console_error_panic_hook"]

# Optional: Profile for release builds (wasm-pack uses --release by default)
# [profile.release]
# lto = true
# opt-level = 's' # Optimize for size